### ISSUE TITLE
Is there going to support ROS1 testing?

### ISSUE THREAD

**Issue by lktc420** [ApexAI/performance_test#35]
Great Work!
May i ask is this going to support ROS1 testing?
Cause i want to compare ROS1 vs ROS2 communication performance.

**Comment by deeplearningrobotics** [comment]
@lktc420: Thank you. We considered adding support ROS 1 but it is a bit complicated to integrate ROS 1 message generation into a ROS 2 package. So we do not plan to add this feature. But if you want to contribute we would surely appreciate and merge it.
