### ISSUE TITLE
Build fail on ROS2 newest version

### ISSUE THREAD

**Issue by lktc420** [ApexAI/performance_test#40]
fail log:
`/home/lktc420/perf_test_ws/src/performance_test/performance_test/src/communication_abstractions/resource_manager.cpp:55:15: error: ‘class eprosima::fastrtps::rtps::RTPSParticipantAttributes’ has no member named ‘defaultSendPort’
   PParam.rtps.defaultSendPort = 11511;
               ^~~~~~~~~~~~~~~`

since like fastrtps 1.7.0 remove defaultSendPort attr.
If i remove the defaultSendPort code, will the test be affected? Do you have plan to build on newest fastrtps?

**Comment by deeplearningrobotics** [comment]
@lktc420: I don't think not setting the port will affect the metrics.

We will add support for ROS 2 Crystal in the next weeks.
