### ISSUE TITLE
performance_test_file_reader.py not working

### ISSUE THREAD

**Issue by alsora** [ApexAI/performance_test#41]
Hi,

I'm trying to run the example provided in the README, but I can't plot the results.

```
mkdir experiment
cd experiment
ros2 run performance_test perf_test -c ROS2 -l log -t Array1k --max_runtime 10
ros2 run performance_test performance_test_file_reader.py .

```

With error

> Skipping .
> Parsing file:./log_Array1k_13-02-2019_16-28-14
> Could not parse file: ./log_Array1k_13-02-2019_16-28-14
> 
> 

Do you know why?

Thank you

**Comment by akifusenet** [comment]
Try updating the line 79 of performance_test_file_reader.py file 
from
`N = 15  # Number of line to skip before CSV data starts.`
to
`N = 17  # Number of line to skip before CSV data starts.`

Akif,

**Comment by alsora** [comment]
It works.
Started a PR to fix it.
