### ISSUE TITLE
Plotter Tool Cosmetic Improvements

### ISSUE THREAD

**Issue by deeplearningrobotics** [ApexAI/performance_test#47]
The performance test plotter tool can use some small cosmetic improvements:

* The result section in the middle should clearly state that those are the averages of the aggregated data.
* The `T_experiment` field should be removed as taking the mean of the runtime does not make a lot of sense.
* Unnamed pandas rows should not show up in the table. 
* Add QOS. In the old report and in the log file they look like this:  "Reliability: BEST_EFFORT Durability: VOLATILE History kind: KEEP_LAST History depth: 1000"
* Resource usage => Resource usage (http://man7.org/linux/man-pages/man2/getrusage.2.html)
* min in the right plot => ru_minflt
* max in the right plot => ru_majflt
* nivcsw => ru_nivcsw

**Comment by dejanpan** [comment]
This was done here: https://github.com/ApexAI/performance_test/pull/49
