### ISSUE TITLE
When I compiled the package under unbuntu-16.04, I got an error.

### ISSUE THREAD

**Issue by qingmingjie** [ApexAI/performance_test#8]
Array16k_PubSubTypes.cxx:47:61: error: ‘SerializedPayload_t’ has not been declared
             bool Array16k_PubSubType::serialize(void *data, SerializedPayload_t *payload)

The namespace of “SerializedPayload_t” is "eprosima::fastrtps::rtps",However, in the files generated by "performance_test" through idlgen tool, the namespace becomes "eprosima::fastrtps". so I have to add "using namespace eprosima::fastrtps::rtps;" in many related documents.This is the bug of idlgen tool !

**Comment by qingmingjie** [comment]
The namespace of “SerializedPayload_t” is "eprosima::fastrtps::rtps",However, in the file generated by "performance_test" through idlgen tool, the namespace becomes "eprosima::fastrtps". maybe this is because of the way of declaration of namespace. Take "TopicDataType.h" for example: "namespace eprosima{namespace fastrtps ... {RTPS_DllAPI virtual bool serialize(void* data, rtps::SerializedPayload_t* payload) = 0;}}"

**Comment by deeplearningrobotics** [comment]
@qingmingjie: Which version of ROS 2 are you using? If you are using bouncy can you try to use this branch: https://github.com/ApexAI/performance_test/tree/memory_check? I fixed there various issues regarding Bouncy and this will become master soon.

The IDL  generators for different FastRTPS produce incompatible code.

**Comment by qingmingjie** [comment]
@deeplearningrobotics: You are right, the "memory_check" branch add the additional path in "perf_test_ws/src/performance_test/performance_test/src/idlgen/fast_rtps/CMakeLists.txt". Many thanks!
