### ISSUE TITLE
Helper scripts meant to be run with ros2 run must be executable

### ISSUE THREAD

**Issue by pbaughman** [ApexAI/performance_test#83]
When attempting to follow the instructions under "Plot results" in the readme.md file, I encountered the following problem:

```
pete.baughman@ade:/tmp/experiment$ ros2 run performance_test performance_test_file_reader.py .
No executable found
```

These helper scripts need to be marked as executable, or they won't be considered valid targets when they're looked up by `ros2 run`

**Comment by daggarwa** [comment]
@pbaughman I think the performance_test_file_reader.py plotter tool is deprecated. We should remove that and only use `apex_performance_plotter` here : https://github.com/ApexAI/performance_test/tree/master/performance_test/helper_scripts/apex_performance_plotter

**Comment by pbaughman** [comment]
We're removing this script in favor of the apex_performance_plotter
